var exports = module.exports = {};

exports.decide = require("./decide.js")
exports.gif =  require('./gif.js')
exports.gender = require("./gender.js")
exports.doc = require("./doc/doc.js")
exports.meteo = require("./meteo/meteo.js")
exports.pause = require("./pause/pause.js")
exports.topGame = require("./topGame.js")
exports.picture = require("./picture.js")
exports.chuck = require("./chuck.js")
exports.wikipedia = require("./wikipedia.js")
exports.amazon = require("./amazon.js")
exports.trafic = require("./trafic.js")
exports.knowledge = require("./brain/knowledge.js")
exports.brain = require("./brain/brain.js")
exports.writeBrain = require("./brain/writeBrain.js")
exports.beauf = require("./beauf/beauf.js")
exports.translate = require("./translate/translate.js")
exports.insult = require("./insult/insult.js")
exports.police = require("./insult/police.js")
exports.news = require("./news.js")
exports.coin = require("./coin.js")
exports.cat = require("./cat.js")
exports.catFact = require("./catFact.js")
exports.help = require("./doc/help.js")
